-- Auto-generated seed data — TRANSTU Tracker
-- Source: MD Data Appendix (bus posters + transtu.tn + sncft.com.tn cross-check pending — see NOTE at bottom).

DELETE FROM lines;
DELETE FROM terminals;

INSERT INTO terminals (id, slug, name, mode, sort) VALUES (1, 'barcelone', 'Terminus Barcelone', 'bus', 1);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (2, 'bel_fi', 'Terminus Bel Fi', 'bus', 2);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (3, 'sliman_kahia', 'Terminus Sliman Kahia', 'bus', 3);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (4, 'carthage', 'Terminus Carthage', 'bus', 4);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (5, 'mornag', 'Terminus Mornag', 'bus', 5);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (6, 'bab_alioua', 'Terminus Bab Alioua', 'bus', 6);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (7, 'intilaka', 'Terminus Intilaka', 'bus', 7);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (8, 'khereddine', 'Terminus Khereddine', 'bus', 8);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (9, '10_decembre', 'Terminus 10 Décembre', 'bus', 9);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (10, 'charguia', 'Terminus Charguia (El Charguia)', 'bus', 10);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (11, 'ariana', 'Terminus Ariana', 'bus', 11);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (12, 'tunis_marine', 'Tunis Marine', 'bus', 12);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (13, 'tebourba', 'Terminus Tebourba (Traboulet)', 'bus', 13);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (14, 'hadiqat_thameur', 'Hadiqat Thameur', 'bus', 14);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (15, 'menzah', 'Terminus Menzah (El Menzah)', 'bus', 15);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (16, 'ali_belhouane', 'Terminus Ali Belhouane', 'bus', 16);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (17, 'autres', 'Autres lignes', 'bus', 17);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (18, 'metro_tunis_marine', 'Tunis Marine (Métro)', 'metro', 18);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (19, 'tgm_tunis_marine', 'Tunis Marine (TGM)', 'train', 19);
INSERT INTO terminals (id, slug, name, mode, sort) VALUES (20, 'sncft_tunis', 'Tunis (gare SNCFT)', 'train', 20);

INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (1, 'bus', 'TRANSTU', NULL, '9B', 'Hay Thameur', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (2, 'bus', 'TRANSTU', NULL, '10B', 'Cité Ejjadida', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (3, 'bus', 'TRANSTU', NULL, '10T', 'Yasmine', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (4, 'bus', 'TRANSTU', NULL, '17', 'El Btah', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (5, 'bus', 'TRANSTU', NULL, '17B', 'Port Radès', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (6, 'bus', 'TRANSTU', NULL, '19', 'Mourouj Kotto', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (7, 'bus', 'TRANSTU', NULL, '19A', 'Mourouj Chaker', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (8, 'bus', 'TRANSTU', NULL, '19T', 'Cité Ejjadida 1', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (9, 'bus', 'TRANSTU', NULL, '19K', 'Cité Ejjadida 123', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (10, 'bus', 'TRANSTU', NULL, '19T2', 'Cité Ejjadida 1', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (11, 'bus', 'TRANSTU', NULL, '19TH', 'Radès Ghaba', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (12, 'bus', 'TRANSTU', NULL, '19J', 'Mourouj Chaker', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (13, 'bus', 'TRANSTU', NULL, '22', 'Hôpital Grands Brûlés', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (14, 'bus', 'TRANSTU', NULL, '22K', 'Ben Arous', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (15, 'bus', 'TRANSTU', NULL, '22A', 'Yasmine', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (16, 'bus', 'TRANSTU', NULL, '26', 'Mornag', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (17, 'bus', 'TRANSTU', NULL, '26A', 'Mornag via RN1', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (18, 'bus', 'TRANSTU', NULL, '26B', 'Mornag via RN1-Chalet', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (19, 'bus', 'TRANSTU', NULL, '29', 'Bel Fi', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (20, 'bus', 'TRANSTU', NULL, '59Y', 'Mourouj 1', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (21, 'bus', 'TRANSTU', NULL, '60', 'Ibn Sina', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (22, 'bus', 'TRANSTU', NULL, '75', 'Boumhal', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (23, 'bus', 'TRANSTU', NULL, '82', 'Boumhal via RN1', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (24, 'bus', 'TRANSTU', NULL, '714', 'Jamaa El Houda–Kairouan périph.', 1, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (25, 'bus', 'TRANSTU', NULL, '28T', 'Circulaire centre-ville via Mohamed V', 2, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (26, 'bus', 'TRANSTU', NULL, '28S', 'Circulaire centre-ville via 9 Avril', 2, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (27, 'bus', 'TRANSTU', NULL, '28TH', 'Salammbô', 2, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (28, 'bus', 'TRANSTU', NULL, '23', 'Borj El Amri/Hafsia', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (29, 'bus', 'TRANSTU', NULL, '23bis', 'Borj El Amri', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (30, 'bus', 'TRANSTU', NULL, '23B', '20 Mars', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (31, 'bus', 'TRANSTU', NULL, '23TH', 'Sidi Hmida', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (32, 'bus', 'TRANSTU', NULL, '23T', 'Sidi Hmida', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (33, 'bus', 'TRANSTU', NULL, '23J', 'Guerâat', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (34, 'bus', 'TRANSTU', NULL, '23KH', 'Borj Ennour', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (35, 'bus', 'TRANSTU', NULL, '23H', 'Sidi Mediène', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (36, 'bus', 'TRANSTU', NULL, '23TT', 'Tliltch/Ksar Jedid', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (37, 'bus', 'TRANSTU', NULL, '48', 'Cité El Bassatine', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (38, 'bus', 'TRANSTU', NULL, '61', 'Prison Mornaguia', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (39, 'bus', 'TRANSTU', NULL, '90', 'Cité Radio-TV', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (40, 'bus', 'TRANSTU', NULL, '91', 'Cité Hassan Belkhodja', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (41, 'bus', 'TRANSTU', NULL, '92', 'Cité El Bortkal', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (42, 'bus', 'TRANSTU', NULL, '87', 'El Mghira', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (43, 'bus', 'TRANSTU', NULL, '433', 'Tayeb El Mhiri', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (44, 'bus', 'TRANSTU', NULL, '489', '20 Mars', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (45, 'bus', 'TRANSTU', NULL, '94', 'Tebourba/Borj El Amri', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (46, 'bus', 'TRANSTU', NULL, '95', 'Khaled Ibn El Walid', 3, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (47, 'bus', 'TRANSTU', NULL, '10', 'Marché central', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (48, 'bus', 'TRANSTU', NULL, '25', 'Ferch Ennabi', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (49, 'bus', 'TRANSTU', NULL, '25A', 'Cité Riadh', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (50, 'bus', 'TRANSTU', NULL, '25B', 'Bir Jedid 2', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (51, 'bus', 'TRANSTU', NULL, '25T', 'Naassène 1', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (52, 'bus', 'TRANSTU', NULL, '25TH', 'Hay Essalem', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (53, 'bus', 'TRANSTU', NULL, '71', 'Dépôt Zahrouni', 4, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (54, 'bus', 'TRANSTU', NULL, '21', 'Ferch Ennabi', 5, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (55, 'bus', 'TRANSTU', NULL, '21A', 'Jbel Errsass', 5, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (56, 'bus', 'TRANSTU', NULL, '21B', 'Tarhouna El Kadima', 5, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (57, 'bus', 'TRANSTU', NULL, '50', 'Charguia', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (58, 'bus', 'TRANSTU', NULL, '65', 'Cité Zouhour 5', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (59, 'bus', 'TRANSTU', NULL, '72', 'Khaled Ibn El Walid', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (60, 'bus', 'TRANSTU', NULL, '78', 'El Omrane El Aala', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (61, 'bus', 'TRANSTU', NULL, '79', 'Cité El Mechtel', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (62, 'bus', 'TRANSTU', NULL, '32A', 'Sidi Hcine', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (63, 'bus', 'TRANSTU', NULL, '71', 'Dépôt Zahrouni', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (64, 'bus', 'TRANSTU', NULL, '116', 'Tebourba', 6, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (65, 'bus', 'TRANSTU', NULL, '44', 'Kalâat El Andalous', 7, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (66, 'bus', 'TRANSTU', NULL, '44B', 'Cité Manji Slim', 7, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (67, 'bus', 'TRANSTU', NULL, '44T', 'El Jbess', 7, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (68, 'bus', 'TRANSTU', NULL, '48A', 'Douar Hicher', 7, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (69, 'bus', 'TRANSTU', NULL, '57A', 'Centre commercial Nahli', 7, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (70, 'bus', 'TRANSTU', NULL, '58', 'Cité El Ouerdia 2', 8, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (71, 'bus', 'TRANSTU', NULL, '93', 'Sanhaja', 8, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (72, 'bus', 'TRANSTU', NULL, '96', 'El Kbaâ', 8, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (73, 'bus', 'TRANSTU', NULL, '97', 'Cité En Nasim', 8, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (74, 'bus', 'TRANSTU', NULL, '98', 'Jlou', 8, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (75, 'bus', 'TRANSTU', NULL, '6', 'Sidi Sfiane', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (76, 'bus', 'TRANSTU', NULL, '6B', 'Cité El Mellaha', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (77, 'bus', 'TRANSTU', NULL, '18T', 'Carthage', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (78, 'bus', 'TRANSTU', NULL, '27', 'Radès plage/Rawad Chatt', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (79, 'bus', 'TRANSTU', NULL, '27A', 'Cité El Ghazala', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (80, 'bus', 'TRANSTU', NULL, '27T', 'Sidi Omrane', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (81, 'bus', 'TRANSTU', NULL, '44J', 'Kalâat El Andalous', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (82, 'bus', 'TRANSTU', NULL, '27J', 'Ariana Berarja', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (83, 'bus', 'TRANSTU', NULL, '47', 'Halk El Oued', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (84, 'bus', 'TRANSTU', NULL, '62', 'Cité El Bekri', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (85, 'bus', 'TRANSTU', NULL, '62A', 'Sidi Omrane', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (86, 'bus', 'TRANSTU', NULL, '35T', 'Nour Jaafar', 9, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (87, 'bus', 'TRANSTU', NULL, '20TH/K+', 'Marsa Cammart', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (88, 'bus', 'TRANSTU', NULL, '27B', 'Rawad Chatt', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (89, 'bus', 'TRANSTU', NULL, '44TH', 'Jamaa Oued Lil', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (90, 'bus', 'TRANSTU', NULL, '44TH2', 'Sidi Thabet', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (91, 'bus', 'TRANSTU', NULL, '514', 'Cité Tadhamen', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (92, 'bus', 'TRANSTU', NULL, '514B', 'Cité Tadhamen', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (93, 'bus', 'TRANSTU', NULL, '515', 'Dépôt Zahrouni', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (94, 'bus', 'TRANSTU', NULL, '515A', 'Cité Zouhour 5', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (95, 'bus', 'TRANSTU', NULL, '515B', 'Cité Zouhour 5', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (96, 'bus', 'TRANSTU', NULL, '533', 'Cité 20 Mars', 10, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (97, 'bus', 'TRANSTU', NULL, '18', 'Cité Manji Slim', 11, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (98, 'bus', 'TRANSTU', NULL, '18B', 'Sidi Salah', 11, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (99, 'bus', 'TRANSTU', NULL, '44A', 'Kalâat El Andalous', 11, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (100, 'bus', 'TRANSTU', NULL, '47A', 'Menzah 9', 11, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (101, 'bus', 'TRANSTU', NULL, '460', 'Manouba', 11, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (102, 'bus', 'TRANSTU', NULL, '5', 'Charguia', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (103, 'bus', 'TRANSTU', NULL, '5T', 'Menzah 6', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (104, 'bus', 'TRANSTU', NULL, '5TH', 'Cité Nasr', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (105, 'bus', 'TRANSTU', NULL, '11', 'Jebel Ahmar', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (106, 'bus', 'TRANSTU', NULL, '28J', 'Lac-Kram', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (107, 'bus', 'TRANSTU', NULL, '35B', '10 Décembre', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (108, 'bus', 'TRANSTU', NULL, '36', 'Ministère des Affaires Étrangères', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (109, 'bus', 'TRANSTU', NULL, '38B', 'El Omrane El Aala', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (110, 'bus', 'TRANSTU', NULL, '38T', 'Jardins Menzah 1&2', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (111, 'bus', 'TRANSTU', NULL, '43B', 'Er Rabta', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (112, 'bus', 'TRANSTU', NULL, '50A', 'Intilaka', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (113, 'bus', 'TRANSTU', NULL, '51A', 'Cité Nasr', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (114, 'bus', 'TRANSTU', NULL, '77', 'Kalâat El Andalous', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (115, 'bus', 'TRANSTU', NULL, '527B', 'Kouriat Jaafar', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (116, 'bus', 'TRANSTU', NULL, '104', 'Université Manouba', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (117, 'bus', 'TRANSTU', NULL, '347', 'La Marsa', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (118, 'bus', 'TRANSTU', NULL, '635', 'Sahet Sla', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (119, 'bus', 'TRANSTU', NULL, '—', 'Aéroport Tunis-Carthage', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (120, 'bus', 'TRANSTU', NULL, '635A', 'Charguia', 12, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (121, 'bus', 'TRANSTU', NULL, '116/', 'Traboulet Kbaâ', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (122, 'bus', 'TRANSTU', NULL, '42/', 'Traboulet Kbaâ', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (123, 'bus', 'TRANSTU', NULL, '16B', 'Traboulet Khereddine', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (124, 'bus', 'TRANSTU', NULL, '42T', 'Zone Industrielle Manouba', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (125, 'bus', 'TRANSTU', NULL, '46', 'Borj Toumi', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (126, 'bus', 'TRANSTU', NULL, '66', 'Dkhila', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (127, 'bus', 'TRANSTU', NULL, '542', 'Charguia', 13, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (128, 'bus', 'TRANSTU', NULL, '4A', 'Cité Sebrolls', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (129, 'bus', 'TRANSTU', NULL, '6S', 'Hôpital pneumo Ariana', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (130, 'bus', 'TRANSTU', NULL, '12', 'Cité Zitouna', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (131, 'bus', 'TRANSTU', NULL, '15', 'Cité Zouhour', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (132, 'bus', 'TRANSTU', NULL, '15A', 'El Herraria', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (133, 'bus', 'TRANSTU', NULL, '15B', 'Cité Zouhour 4', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (134, 'bus', 'TRANSTU', NULL, '20', 'Cité Boussalsla', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (135, 'bus', 'TRANSTU', NULL, '20/', 'Lac', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (136, 'bus', 'TRANSTU', NULL, '20A', 'Bahr Azrek', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (137, 'bus', 'TRANSTU', NULL, '20B', 'Cammart', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (138, 'bus', 'TRANSTU', NULL, '20T', 'Carthage', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (139, 'bus', 'TRANSTU', NULL, '32', 'Cité Zouhour 5', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (140, 'bus', 'TRANSTU', NULL, '32B', 'Borj Chaker', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (141, 'bus', 'TRANSTU', NULL, '32T', 'Dépôt Zahrouni', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (142, 'bus', 'TRANSTU', NULL, '32TH', 'Sidi Hcine', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (143, 'bus', 'TRANSTU', NULL, '33', 'El Mghira', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (144, 'bus', 'TRANSTU', NULL, '33A', 'Bouhamed', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (145, 'bus', 'TRANSTU', NULL, '33/', 'Cité Hassan', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (146, 'bus', 'TRANSTU', NULL, '33B', 'Cité 20 Mars', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (147, 'bus', 'TRANSTU', NULL, '33T', '25 Juillet', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (148, 'bus', 'TRANSTU', NULL, '34', 'Zaouiet Bouâziz', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (149, 'bus', 'TRANSTU', NULL, '34A', 'Prison civile Mornaguia', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (150, 'bus', 'TRANSTU', NULL, '63', 'El Mansoura 2', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (151, 'bus', 'TRANSTU', NULL, '80', 'El Bekri', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (152, 'bus', 'TRANSTU', NULL, '88', 'Karya El Waha', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (153, 'bus', 'TRANSTU', NULL, '88A', 'Cité Jebri', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (154, 'bus', 'TRANSTU', NULL, '89', 'Cité Mohamed Ali', 14, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (155, 'bus', 'TRANSTU', NULL, '24', 'Cité Essaâda', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (156, 'bus', 'TRANSTU', NULL, '24/', 'Cité El Ilmi', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (157, 'bus', 'TRANSTU', NULL, '24A', 'Aouina', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (158, 'bus', 'TRANSTU', NULL, '24TH', 'Chabdda', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (159, 'bus', 'TRANSTU', NULL, '24J', 'Sidi Farhat', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (160, 'bus', 'TRANSTU', NULL, '24H', 'Cité Hached', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (161, 'bus', 'TRANSTU', NULL, '24H2', 'Cité Nasr', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (162, 'bus', 'TRANSTU', NULL, '24KH', 'Cité El Amel', 15, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (163, 'bus', 'TRANSTU', NULL, '3A', 'Ksar Saïd 2', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (164, 'bus', 'TRANSTU', NULL, '3TH', 'Institut Cité Tadhamen', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (165, 'bus', 'TRANSTU', NULL, '14A', 'El Omrane El Aala', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (166, 'bus', 'TRANSTU', NULL, '14T', 'Cité El Bassatine', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (167, 'bus', 'TRANSTU', NULL, '16', 'Habibia 2', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (168, 'bus', 'TRANSTU', NULL, '16T', 'Cité El Ouerdia 2', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (169, 'bus', 'TRANSTU', NULL, '16TH', 'Jlou', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (170, 'bus', 'TRANSTU', NULL, '30', 'Cité Tahrir', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (171, 'bus', 'TRANSTU', NULL, '31', 'Kantra Bizerte', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (172, 'bus', 'TRANSTU', NULL, '31A', 'Bach Hamba', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (173, 'bus', 'TRANSTU', NULL, '31B', 'Kalâat El Andalous', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (174, 'bus', 'TRANSTU', NULL, '31T/31T2', 'Charfech', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (175, 'bus', 'TRANSTU', NULL, '42', 'Tebourba', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (176, 'bus', 'TRANSTU', NULL, '42A', 'El Mansoura', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (177, 'bus', 'TRANSTU', NULL, '42B', 'Zouitina', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (178, 'bus', 'TRANSTU', NULL, '55', 'Douar Hicher', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (179, 'bus', 'TRANSTU', NULL, '56', 'Khaled Ibn El Walid', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (180, 'bus', 'TRANSTU', NULL, '64', 'Cité Tahrir', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (181, 'bus', 'TRANSTU', NULL, '68', 'Cité 18 Janvier', 16, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (182, 'bus', 'TRANSTU', NULL, '16A', 'M.P. Manouba', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (183, 'bus', 'TRANSTU', NULL, '32A', 'Sidi Hcine', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (184, 'bus', 'TRANSTU', NULL, '36B', 'Ministère Affaires Étrangères', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (185, 'bus', 'TRANSTU', NULL, '37', 'Borj Sedria', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (186, 'bus', 'TRANSTU', NULL, '39', 'Radès Ghaba', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (187, 'bus', 'TRANSTU', NULL, '40+52', 'Institut Carthage', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (188, 'bus', 'TRANSTU', NULL, '43', 'Er Rabta', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (189, 'bus', 'TRANSTU', NULL, '47T', 'Manji Slim', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (190, 'bus', 'TRANSTU', NULL, '49', 'Hôpital Tebourba', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (191, 'bus', 'TRANSTU', NULL, '52B', 'Carthage', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (192, 'bus', 'TRANSTU', NULL, '52T', 'Institut Carthage', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (193, 'bus', 'TRANSTU', NULL, '54', 'Mourouj 5', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (194, 'bus', 'TRANSTU', NULL, '154A', 'Cité Essaâda', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (195, 'bus', 'TRANSTU', NULL, '154/', 'Cité Essaâda', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (196, 'bus', 'TRANSTU', NULL, '54B', 'CTGB', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (197, 'bus', 'TRANSTU', NULL, '74', 'Tunis Marine', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (198, 'bus', 'TRANSTU', NULL, '74B', 'Bab Saâdoun', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (199, 'bus', 'TRANSTU', NULL, '81A', 'Mourouj 6+4', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (200, 'bus', 'TRANSTU', NULL, '84/85/86', 'El Mghira', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (201, 'bus', 'TRANSTU', NULL, '147', 'Port La Goulette', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (202, 'bus', 'TRANSTU', NULL, '247', 'Rawad Chatt', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (203, 'bus', 'TRANSTU', NULL, '410B', 'Sliman Kahia', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (204, 'bus', 'TRANSTU', NULL, '527', 'Cité El Ghazala', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (205, 'bus', 'TRANSTU', NULL, '527A', 'Kouriat Jaafar', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (206, 'bus', 'TRANSTU', NULL, '574', 'Charguia', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (207, 'bus', 'TRANSTU', NULL, '3710', 'Borj Sedria', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (208, 'bus', 'TRANSTU', NULL, '3J', 'Cité Nasr', 17, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (209, 'metro', 'TRANSTU', NULL, '1', 'Ben Arous', 18, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (210, 'metro', 'TRANSTU', NULL, '2', 'Ariana', 18, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (211, 'metro', 'TRANSTU', NULL, '3', 'Ibn Khaldoun', 18, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (212, 'metro', 'TRANSTU', NULL, '4', 'Khereddine', 18, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (213, 'metro', 'TRANSTU', NULL, '5', 'Intilaka', 18, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (214, 'metro', 'TRANSTU', NULL, '6', 'Mourouj 4', 18, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (215, 'train', 'TRANSTU', 'tgm', 'TGM', 'Tunis Marine ↔ La Marsa Plage, via La Goulette, Le Kram, Carthage, Sidi Bou Saïd', 19, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (216, 'train', 'SNCFT', 'grandes_lignes', 'Tunis ↔ Sud-Est', 'Tunis – Sousse – Monastir – Mahdia – Sfax – Gabès – Gafsa – Metlaoui – Tozeur', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (217, 'train', 'SNCFT', 'grandes_lignes', 'Tunis ↔ Frontière algérienne', 'Tunis – Béja – Jendouba – Ghardimaou – Souk Ahras – Annaba', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (218, 'train', 'SNCFT', 'grandes_lignes', 'Tunis ↔ Bizerte', 'Tunis – Manouba – Mateur – Tinja – Bizerte', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (219, 'train', 'SNCFT', 'grandes_lignes', 'Tunis ↔ Le Kef', 'Tunis – Gaafour – Dahmani – Le Kef – Jrissa – Kalaa Khasba', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (220, 'train', 'SNCFT', 'grandes_lignes', 'Tunis ↔ Nabeul', 'Tunis – Nabeul', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (221, 'train', 'SNCFT', 'grandes_lignes', 'Ligne A (Banlieue)', 'Tunis – Erriadh', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (222, 'train', 'SNCFT', 'grandes_lignes', 'Ligne D (Banlieue)', 'Tunis – Gobaa City', 20, NULL, 1);
INSERT INTO lines (id, mode, operator, train_kind, code, destination, terminal_id, route_summary, active) VALUES (223, 'train', 'SNCFT', 'grandes_lignes', 'Ligne E (Banlieue)', 'Tunis – Bougatfa', 20, NULL, 1);

-- NOTE: first_departure / last_departure / frequency_min left NULL — enter via
-- the Direction admin back-office (updateLineSchedule) from the source posters,
-- per the MD brief's own instruction not to hardcode timetables in the UI.
-- NOTE: destination spellings are best-effort Latin transliterations; verify
-- against https://www.transtu.tn/fr/ and https://www.sncft.com.tn/ before go-live.
